name: sartia_global
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  get: ^4.1.4
  bot_toast: ^4.0.1
  get_storage: ^2.0.2
  connectivity_plus: ^1.0.1
  internet_connection_checker: ^0.0.1+2
  badges: ^2.0.1
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  google_sign_in: ^5.0.5
  pin_code_fields: ^7.0.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
